version: '3.8'

services:
  analytics:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    networks:
      - analytics-network
    volumes:
      - ./app/temp:/app/temp

networks:
  analytics-network:
    driver: bridge
